config/routes.rb
Rails.application.routes.draw do
	devise_for :users

	resources :users, :only => [:show, :edit]

	match 'account' => 'users#show', via: [:get, :post]

	resources :links, :path => '/'
	resources :links do
		member do
			put "like", to: "links#like"
			put "unlike", to: "links#unlike"
		end
	end

	root "links#index"

end

app/models/discip.rb
class Discip < ActiveRecord::Base
end

app/models/kind.rb
class Kind < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :user
	acts_as_votable

	def prune
		self.url = self.url.match(/\/\/(www\.)?(.*)(\/)?/)[2].chomp("/")
	end

	before_create :prune

	extend FriendlyId
	friendly_id :name, use: :slugged

	validates_presence_of :name, :url
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :links
	acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_action :set_link, only: [:edit, :update, :destroy]
	before_filter :authenticate_user!, except: [:index, :show]

	def like
		@link = Link.friendly.find(params[:id])
		@link.like_by current_user
		redirect_to :back
	end

	def unlike
		@link = Link.friendly.find(params[:id])
		@link.unliked_by current_user
		redirect_to :back
	end

	# GET /links
	# GET /links.json
	def index
		@links = Link.all.order('name ASC')
	end

	# GET /links/new
	def new
		@link = current_user.links.build
	end

	# GET /links/1/edit
	def edit
	end

	# POST /links
	# POST /links.json
	def create
		@link = current_user.links.build(link_params)

		respond_to do |format|
			if @link.save
				format.html { redirect_to root_path, notice: 'Link was successfully created.' }
				format.json { render :show, status: :created, location: @link }
			else
				format.html { render :new }
				format.json { render json: @link.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /links/1
	# PATCH/PUT /links/1.json
	def update
		respond_to do |format|
			if @link.update(link_params)
				format.html { redirect_to root_path, notice: 'Link was successfully updated.' }
				format.json { render :show, status: :ok, location: @link }
			else
				format.html { render :edit }
				format.json { render json: @link.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /links/1
	# DELETE /links/1.json
	def destroy
		@link.destroy
		respond_to do |format|
			format.html { redirect_to root_path, notice: 'Link was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_link
		@link = Link.friendly.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def link_params
		params.require(:link).permit(:name, :url, :color, :desc, :discip, :kind)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = current_user

		@likes = @user.find_liked_items
		@submits = Link.all.where(:user_id => @user.id).order('name ASC')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_link.html.haml
#links
  - @links.each do |link|
    .link
      %a{href: "//#{link.url}", target: "_blank", style: "background: #{link.color}"}
        %h3= link.title
        
      .info
        - unless link.desc.nil?
          %p= link.desc

        %div
          %a= link.url

        .like
          = link_to "Like (#{link.votes_for.size})", like_link_path(link), method: :put

        .ctrl
          - if user_signed_in?
            - if link.user_id = current_user.id
              = link_to current_user.email, "account"
              = link_to "Edit", "links/#{link.slug}/edit"

app/views/layouts/_side.html.haml
#side
  #cats
    = link_to "Launchpad", root_path

  #acct
    - if user_signed_in?
      = link_to "Submit link", new_link_path
      = link_to "Account", "/account"
      = link_to "Sign out", destroy_user_session_path, :method => :delete

    - else
      = link_to "Sign up", new_user_registration_path
      = link_to "Sign in", new_user_session_path

#tog
  = fa_icon "angle-right"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Websites for enthusiasts of technical mediums
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/side"

    #disp
      = yield

app/views/links/_form.html.haml
= form_for(@link) do |f|
  - if @link.errors.any?
    #error_explanation
      %h2
        = pluralize(@link.errors.count, "error")
        prohibited this link from being saved:
      %ul
        - @link.errors.full_messages.each do |message|
          %li= message
  
  #link_form
    .field
      = f.label :name
      = f.text_field :name, :placeholder => 'Name of service, website if not applicable'

    .field
      = f.label :url, 'URL'
      = f.text_field :url, :placeholder => 'https://www.website.com/'

    .field
      = f.label :discip, 'Discipline'
      = f.select :discip, Discip.all.collect {|d| [d.name]}

    .field
      = f.label :kind, 'Kind'
      = f.select :kind, Kind.all.collect {|k| [k.name]}

    .field#color
      = f.label :color, 'CSS Color'
      %div
        #color_box
        = f.text_field :color, :placeholder => '#000000 / rgb(000, 000, 000), word / black'

    .field
      = f.label :desc, 'Description'
      = f.text_area :desc, :placeholder => 'General justification of the website and how it works'

    .actions
      = f.submit 'Submit'

app/views/links/edit.html.haml
= render 'form'

= link_to 'Delete', @link, :method => :delete, :confirm => "Are you sure?" 

app/views/links/index.html.haml
#links
  - @links.each do |link|
    .link
      %a{href: "//#{link.url}", target: "_blank", style: "background: #{link.color}"}
        %h3= link.name
        
      .info
        - if link.desc.present?
          %p= link.desc

        .stats
          %h5
            = fa_icon "link"
            = link.url

          %h5
            - if user_signed_in?
              - if current_user.voted_for? link
                %a{"data-method" => "put", :href => unlike_link_path(link), :rel => "nofollow"}
                  = fa_icon "thumbs-up"
                  = link.votes_for.size
              
              - else
                %a{"data-method" => "put", :href => like_link_path(link), :rel => "nofollow"}
                  = fa_icon "thumbs-o-up"
                  = link.votes_for.size

          - if link.discip.present?
            %h5
              = fa_icon "pencil"
              = link.discip

          - if link.kind.present?
            %h5
              = fa_icon "cogs"
              = link.kind

          - if user_signed_in?
            .ctrl
              - if link.user_id = current_user.id
                = link_to "Edit", edit_link_path(link)

app/views/links/new.html.haml
= render 'form'

app/views/users/show.html.haml
%h3
  = @user.email

  = link_to "Edit settings", "/users/edit"

%hr

%h3
  Likes

%hr

#links
  - @likes.each do |link|
    - if link.present?
      .link
        %a{href: "//#{link.url}", target: "_blank", style: "background: #{link.color}"}
          %h3= link.name

        .info
          - if link.desc.present?
            %p= link.desc

          .stats
            %h5
              = fa_icon "link"
              = link.url

            %h5
              - if current_user.voted_for? link
                %a{"data-method" => "put", :href => unlike_link_path(link), :rel => "nofollow"}
                  = fa_icon "thumbs-up"
                  = link.votes_for.size
              
              - else
                %a{"data-method" => "put", :href => like_link_path(link), :rel => "nofollow"}
                  = fa_icon "thumbs-o-up"
                  = link.votes_for.size

          - if link.discip.present?
            %h5
              = fa_icon "pencil"
              = link.discip

          - if link.kind.present?
            %h5
              = fa_icon "cogs"
              = link.kind

          .ctrl
            - if link.user_id = current_user.id
              = link_to "Edit", "links/#{link.slug}/edit"

%h3
  Submitted

%hr

#links
  - @submits.each do |link|
    .link
      %a{href: "//#{link.url}", target: "_blank", style: "background: #{link.color}"}
        %h3= link.name

      .info
        - if link.desc.present?
          %p= link.desc

        .stats
          %h5
            - if current_user.voted_for? link
              %a{"data-method" => "put", :href => unlike_link_path(link), :rel => "nofollow"}
                = fa_icon "thumbs-up"
                = link.votes_for.size
            
            - else
              %a{"data-method" => "put", :href => like_link_path(link), :rel => "nofollow"}
                = fa_icon "thumbs-o-up"
                = link.votes_for.size

          %h5
            = fa_icon "link"
            = link.url

          - if link.discip.present?
            %h5
              = fa_icon "pencil"
              = link.discip

          - if link.kind.present?
            %h5
              = fa_icon "cogs"
              = link.kind

        .ctrl
          = link_to "Edit", "#{link.slug}/edit"